import Link from "next/link";
import { Button } from "@/components/ui/button";
import { BrainCircuit, ArrowRight, Sparkles, Gamepad2, BarChart3, Shield } from "lucide-react";

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      {/* Nav */}
      <header className="border-b border-zinc-200 dark:border-zinc-800">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-2 font-bold text-xl">
            <BrainCircuit className="h-7 w-7 text-purple-600" />
            Nexboard
          </div>
          <div className="flex items-center gap-4">
            <Link href="/auth/signin">
              <Button variant="ghost">Sign In</Button>
            </Link>
            <Link href="/auth/signup">
              <Button>Get Started</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="flex-1">
        <div className="mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">
              AI-Powered{" "}
              <span className="bg-gradient-to-r from-purple-600 to-blue-500 bg-clip-text text-transparent">
                Onboarding
              </span>{" "}
              for the Modern Workforce
            </h1>
            <p className="mt-6 text-lg text-zinc-600 dark:text-zinc-400">
              Personalized learning paths, interactive AI simulations, and real-time feedback
              accelerate new hire readiness — from day one.
            </p>
            <div className="mt-10 flex items-center justify-center gap-4">
              <Link href="/auth/signup">
                <Button size="lg" className="gap-2">
                  Start Free Trial <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
              <Link href="/auth/signin">
                <Button variant="outline" size="lg">
                  Sign In
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="border-t border-zinc-200 py-20 dark:border-zinc-800">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <h2 className="text-center text-3xl font-bold">Everything you need to onboard faster</h2>
          <div className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {[
              {
                icon: Sparkles,
                title: "AI Learning Paths",
                desc: "Personalized tasks generated by AI, adaptive to each new hire's role and skill level.",
              },
              {
                icon: Gamepad2,
                title: "Interactive Playgrounds",
                desc: "Code review arena, email simulations, and debugging scenarios with instant AI feedback.",
              },
              {
                icon: BarChart3,
                title: "Progress Analytics",
                desc: "Real-time dashboards for new hires, mentors, and leadership to track readiness.",
              },
              {
                icon: Shield,
                title: "Enterprise Security",
                desc: "SSO, MFA, role-based access, and full audit trails for compliance.",
              },
            ].map((feature) => {
              const Icon = feature.icon;
              return (
                <div
                  key={feature.title}
                  className="rounded-xl border border-zinc-200 p-6 dark:border-zinc-800"
                >
                  <Icon className="h-8 w-8 text-purple-600" />
                  <h3 className="mt-4 font-semibold text-lg">{feature.title}</h3>
                  <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">{feature.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-zinc-200 py-8 dark:border-zinc-800">
        <div className="mx-auto max-w-7xl px-4 text-center text-sm text-zinc-500 sm:px-6 lg:px-8">
          &copy; {new Date().getFullYear()} Nexboard. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
